development:
  adapter: postgresql
  encoding: unicode
  database: db/store_development
  pool: 5
  username: acib708
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: db/store_test
  pool: 5
  username: acib708
  password: